### ISSUE TITLE
How to prevent external domain access

### ISSUE THREAD

**Issue by mordecai87** [Smile-SA/node-pushserver#14]
Hi, first congratulations for this awesome work. My question is, how can you prevent people to send push notifications from a public ip or domain? if someone can access to http://domain:port/send, it can be something dangerous...Thank you!!

**Comment by marob** [comment]
Hi,

this is a network configuration matter that isn't related to the node-pushserver.
I suggest you add a reverse proxy in front of the node-pushserver and manage the security with the reverse proxy.

You could add, with this reverse proxy, basic authentication, https, IP filtering, ...
Of course, you should also disable direct access to node-pushserver (access it only through the reverse proxy).

Regards
