### ISSUE TITLE
Error 513

### ISSUE THREAD

**Issue by mikkela** [Smile-SA/node-pushserver#17]
Hi
When I use the pushserver on my mac, everything works ok. However, when I use the same setup on a Windows machine, it gives me an error 513. I suspect it is the path to the cert and key that creates the problem. I have no idea of how to setup the path on a Windows machine. Please help me

My config file:

{
  "webPort": 17200,
 
    "mongodbUrl": "mongodb://scaut:scaut@localhost/pushserver_dev",
 
    "gcm": {
        "apiKey": "YOUR_API_KEY_HERE"
    },
 
    "apn": {
        "connection": {
            "gateway": "gateway.sandbox.push.apple.com",
            "cert": "/data/pushserver/cert.pem",
            "key": "/data/pushserver/key.pem"
        },
        "feedback": {
            "address": "feedback.sandbox.push.apple.com",
            "cert": "/data/pushserver/cert.pem",
            "key": "/data/pushserver/key.pem",
            "interval": 43200,
            "batchFeedback": true
        }
    }
}

**Comment by marob** [comment]
Hi,

I think the path should be of the form "C:\path\to\pemfile", but I haven't tested.

**Comment by mikkela** [comment]
You're right. The path needs to be as you said. That was not the problem though. I also needed to configure my password and install and open ssl client on my Windows server. 

http://support.verivo.com/entries/22063752-Debugging-iOS-push-connectivity-across-a-network

gave some debugging help
