### ISSUE TITLE
A way to secure connections?

### ISSUE THREAD

**Issue by Maddis1337** [Smile-SA/node-pushserver#18]
Hi, I hope that this is not too offtopic for this issue page:
I want to set up the server on an external maschine (multiple heroku instances). Is there a way to verify (for example with RSA keys) to make sure that only a specific application/server can send out push notifications?

**Comment by marob** [comment]
Hi,

I think it is a little off-topic indeed, as it is Heroku-related. I don't know Heroku, but I would suggest some kind of out-of-the app authentication, via basic authentication (+ https) for example.

I found a question on stackoverflow that may help you: http://stackoverflow.com/questions/4828616/how-can-i-keep-my-heroku-application-private

Regards
