### ISSUE TITLE
How to expose openshift env variables in example.config.json

### ISSUE THREAD

**Issue by SakyaStelios** [Smile-SA/node-pushserver#20]
How to expose openshift env variables in example.config.json? The format for openshift is:

process.env.OPENSHIFT_MONGODB_DB_URL

How can I set it in the json for config?

**Comment by marob** [comment]
I've added a new option for you: 0baf709babf82df85aea7f7b275880b14b86aa2f

You can launch node-pushserver with the option "-o mongodbUrl=process.env.OPENSHIFT_MONGODB_DB_URL".

Please, tell me if it solves your problem.

Regars

**Comment by marob** [comment]
I've simplified it by adding the possibility to use env var directly in the configuration file.
Just set "mongodbUrl": "process.env.OPENSHIFT_MONGODB_DB_URL" in the config.json.

**Comment by mebibou** [comment]
@marob can you make a new release with those changes? I just installed the module and cannot use `-o` option

**Comment by marob** [comment]
@mebibou I'm not able to publish a new version for now, but you can try the "From git" install.

**Comment by marob** [comment]
0.5.4 version published!
