### ISSUE TITLE
How to expose Appfog env variables in example.config.json

### ISSUE THREAD

**Issue by butchewing** [Smile-SA/node-pushserver#21]
I saw the issue for [OpenShift](https://github.com/Smile-SA/node-pushserver/issues/20). I was wondering how to accomplish this with Appfog as well.

https://support.appfog.com/hc/en-us/articles/202311853-MongoDB#node

**Comment by marob** [comment]
You could create a nodeJS script based on the "Configure MongoDB" sectoin

**Comment by marob** [comment]
You could create a nodeJS script based on the one in the "Configure MongoDB" section of https://support.appfog.com/hc/en-us/articles/202311853-MongoDB#node and then create a shell script that:
- computes the mongoURL from the above mentioned nodeJS script and stores it in a "MONGO_URL" variable
- launches the node-pushserver with the "-o mongodbUrl=$MONGO_URL" option

This way, the node-pushserver should be well configured.
