### ISSUE TITLE
can i send notification to more than 5000 user with your given pushserver 

### ISSUE THREAD

**Issue by maneeshdisodia** [Smile-SA/node-pushserver#28]
hey smile,
this is query not issue
can i send notification to more than 5000 user with your given pushserver. when i read gcm docs they support only 1000 user at a time per request.
 is their any way i can send notification to 5000 user at a time means first 1000.
because by default your server send notification to all register user. 

thanks smile

**Comment by marob** [comment]
Hi,

we don't split in several push if there is more than 1000 users for now. So we have the same limitation as node-gcm (1000 users).

Regards

**Comment by maneeshdisodia** [comment]
ok, thanks marob
