### ISSUE TITLE
failed to configure "node-pushserver" in sails.js app

### ISSUE THREAD

**Issue by anil-codewave** [Smile-SA/node-pushserver#32]
hi all,

I am developing rest api's using sails js with mongodb. I want to implement push notifications for both android and ios. I can not find config.json in my sails app. i am new to sails js and worried to fix this feature in my app, I am trying since last 3days but failed to make it work so please can anyone help me with how to configure this "node-pushserver" in sails js and how to make it work. 

Thanks In Advance..

**Comment by marob** [comment]
Hi,

node-pushserver is NOT in sails.js and shouldn't be hard-linked to any other development.
It is meant to be used as a standalone application requiring node.js and mongodb as dependencies.

Your application should only interact with node-pushserver via its REST API.

As for the config.json, node-pushserver has a sample file called example.config.json that you can copy and edit.

Regards

**Comment by anil-codewave** [comment]
thanks a lot Morob. :)
