### ISSUE TITLE
npm page outdated (database is mongodb not sqlite)

### ISSUE THREAD

**Issue by Nilos** [Smile-SA/node-pushserver#34]
The npm page states that "node-pushserver uses sqlite to store the user / token associations." but it uses mongodb.

**Comment by marob** [comment]
Duplicates #30

**Comment by Nilos** [comment]
Is there any way to install the alpha version? I would much prefer sqlite to mongodb ;)

**Comment by marob** [comment]
It's on my own repo: https://github.com/marob/node-pushserver
Note that it's an alpha version, so it hasn't been fully tested yet.
