### ISSUE TITLE
APNS extra data

### ISSUE THREAD

**Issue by wolfasaeru** [Smile-SA/node-pushserver#38]
What if I need to send extra/custom data to the iOS device. How can I do it?

**Comment by JinlianWang** [comment]
Seems to be the same complaint as another issue. It is supported, using the "payload" field like the following json: 

```
{
    "badge": 0,
    "alert": "Your message here3",
    "sound": "soundName",
    "category": "SWIFT",
    "payload": {"messageFrom": "Caroline"}
}
  ```

**Comment by wolfasaeru** [comment]
Awesome, thanks
