### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by gabrielbazan7** [Smile-SA/node-pushserver#46]
Listening on port 8000...
401

I was able to subscribe new users but when i try to send a message an 401 error appears in console (However success appears in $http post callback). 
This is my config file : 

{
    "webPort":8000,

    "mongodbUrl": "mongodb://localhost",

    "gcm": {
        "apiKey": "The apiKey here"
    }
}

Any idea ? i been trying a lot. The same error appears when i use the the web interface.

**Comment by gabrielbazan7** [comment]
Solved.

**Comment by mjunaidsalaat** [comment]
Can you tell me how you solved it? I'm facing this too.
