### ISSUE TITLE
Sound in Android

### ISSUE THREAD

**Issue by matiu** [Smile-SA/node-pushserver#47]
Hi!

Thanks for this awesome project!

Quick question, how should be the options to send notifications with sound in Android?

thanks!

**Comment by marob** [comment]
Hi!

It should be:
```
{
  "data": {
    "title": "Title",
    "message": "Your message",
    "sound": "mySound"
  }
}
```
You could also try "soundname" instead of "sound" as it seams to be an alias.

Note that you need a mySound.wav (or .mp3 or else?) in the res/raw folder of your Android application.

**Comment by matiu** [comment]
thanks a lot!

On Thu, Jan 21, 2016 at 4:37 PM, Maxime Robert <notifications@github.com>
wrote:

> Hi!
>
> It should be:
>
> {
>   "data": {
>     "title": "Title",
>     "message": "Your message",
>     "sound": "mySound"
>   }
> }
>
> You could also try "soundname" instead of "sound" as it seams to be an
> alias.
>
> Note that you need a mySound.wav (or .mp3 or else?) in the res/raw folder
> of your Android application.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Smile-SA/node-pushserver/issues/47#issuecomment-173685066>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
