### ISSUE TITLE
Notifications to ios are not sent (APN connection not established)

### ISSUE THREAD

**Issue by vijayaa** [Smile-SA/node-pushserver#55]
Throwing uncaughtException: error:0906A068:PEM routines:PEM_do_header:bad password error.
Certificates are valid
telnet gateway.sandbox.push.apple.com 2195 is working fine
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert PushChatCert.pem -key PushChatKey.pem is working fine

**Comment by marob** [comment]
Duplicates argon/node-apn#373

I think your .pem file should not be password protected. Neither node-pusherver nor node-apn (used internally) can guess that password.

**Comment by debjeet-sarkar** [comment]
I guess this issue is resolved and hence needs to be closed , otherwise its misleading for ones searching for open issues.
