### ISSUE TITLE
Notifications to Android are not being displayed on device

### ISSUE THREAD

**Issue by JasonAsbahr** [Smile-SA/node-pushserver#57]
Hi folks, great project!  I've been able to get pushserver to send pushes to iOS devices, but when I try the same with Android devices, I see that the push gets to the device, but it doesn't show up in the Android Notification UI.

Here's the curl command I am using, with the example payload format as shown in the pushserver docs:

curl http://localhost:8000/send \
   -X POST \
   -H "Content-Type: application/json" \
   -d '{
  "users": ["JasonAndroid"],
  "android": {
    "collapseKey": "optional",
    "data": {
      "message": "Your message here"
    }
  },
  "ios": {
    "badge": 0,
    "alert": "Your message here",
    "sound": "soundName"
  }
}'

....which causes the following to appear in adb logs:

I/GCM     (  754): GCM message com.example.myapp 0:1461102606930325%8d57e096fb4a4b60
W/GCM-DMM (  754): broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.example.myapp (has extras) }
D/ConnectivityService(  390): handleInetConditionHoldEnd: net=1, condition=100, published condition=100

...but no notification alert appears to the user.

So pushserver is able to connect with the GCM server and get the message into the device.  It's just not registering in the UI. I've tried several variations on the json format for the push payload, with no difference in results.

However, I have this same device and GCM service registered with Urban Airship and I'm able to send pushes via that service which do show up on device and appear in the notification UI as desired.  The exact same adb log message is received in that case, but it works.  

What am I missing?

Thanks!

Jason

**Comment by marob** [comment]
Hi,

if the device receives the notification, the problem doesn't seem to be "node-pushserver"-related.
It has to be related to the way your device or your application handles notifications.
Can you check in your Android Parameters if you blocked notifications for this application ?

Regards

**Comment by JasonAsbahr** [comment]
Hi, @marob.  The device and application receive push notification from Urban Airship just fine.  That's what makes me wonder what is different about how UA is formatting push payloads versus how node-pushserver is formatting them.

**Comment by marob** [comment]
OK, so the notification send via Urban Airship is addressed to the same Android application as the one you're trying to send notification to with node-pushserver ? I think I misunderstood that. Hence my thought about blocked notification for the app.

Have you tried removing `"collapseKey": "optional",` from the JSON payload ?

**Comment by JasonAsbahr** [comment]
Just did, no luck.

**Comment by marob** [comment]
Sorry, but I've installed a fresh version of node-pushserver and notification works like a charm.
I'm closing this issue as it seems not to be related to node-pushserver.
