### ISSUE TITLE
Android notifications not delivered

### ISSUE THREAD

**Issue by oliverwh** [Smile-SA/node-pushserver#65]
story:
- iOS works like a charm
- Android notifications are not delivered.

That's not about implementation in android device, as it could receive proper notification from firebase console and via simple curl command.

Any chance to turn on debugging in the app or some piece of advice?

**Comment by marob** [comment]
* make sure your gcm.apiKey is OK
* make sur the token(s) of your android users in your node-pushserver correspond to the ones issued by your android app
* you should log this token in your app when registering to GCM to be able to compare it with the one stored in node-pushserver

**Comment by oliverwh** [comment]
hey, thx for reply.

- exactly same as I use for curl
- exactly same token which I send with curl command
- what do you mean by log?  For simplicity of use, I've inserted new user with this token to database directly with type android

this is my curl command:
`curl --header "Authorization: key=AIza.....-C6G6k" --header Content-Type:"application/json" https://gcm-http.googleapis.com:443/gcm/send  -d '{ "to" : "eyeCrv3k5GE:APA91bFpK2G_h4P374ob98gQ64nO_v3-C_gSseOUWTTuenPU_......", "notification" : { "title" : "test", "body" : "test"}}'`

**Comment by marob** [comment]
If you curl http://domain:port/users/{user}/associations with your user, does the token in the response matches "eyeCrv3k5GE:APA91bFpK2G_h4P374ob98gQ64nO_v3-C_gSseOUWTTuenPU_......" ?

**Comment by oliverwh** [comment]
yes, exactly

**Comment by marob** [comment]
Then, if you POST on http://domain:port/send with the following content:
```
{
  "users": ["user1"],
  "android": {
    "collapseKey": "optional",
    "data": {
      "message": "Your message here"
    }
  }
}
```

What is the response? Is there any log on the pushserver?

Also, make sure you set "Content-Type: application/json" header on your POST. Example:
`curl 'http://domain:port/send' -H 'Content-Type: application/json' --data-binary '{"users":["user1"],"android":{"collapseKey":"optional","data":{"message":"You message here"}}}'`


You may also enable debug mode of node-gcm: https://github.com/ToothlessGear/node-gcm/tree/b04a9e188ee9f6d091b343d52197031d6424aae9#debug

**Comment by oliverwh** [comment]
The funny thing that node-gcm works fine

here us the debug:

```
{ multicast_id: 4794498738207951000,
  success: 1,
  failure: 0,
  canonical_ids: 0,
  results: [ { message_id: '0:1475362507203960%2609005326090053' } ] }
```

**Comment by oliverwh** [comment]
So by playing around, I found that issue is related to parsed payload inside app.

If I replace function buildPayload in GCMPusher.js with following:

```
var buildPayload = function (options) {
    var notif = new gcm.Message(options.payload);

    //notif.addData('hello', 'world');
    //notif.addNotification('title', 'TEST');
    notif.addNotification('icon', 'ic_launcher');
    //notif.addNotification('body', 'World');
    notif.addNotification('sound', 'enabled');

    return notif;
}
```

I could receive a notification sent from push interface. Just need to figure out why payload is not processed.
I assume it will not work on your side as well.

**Comment by marob** [comment]
Surprisingly, I didn't encounter any problem on my end while trying to send an android notification with node-pushserver.

Maybe "icon" is now required? But it worked for me without this parameter.

**Comment by oliverwh** [comment]
Dunno, but this was the only way for my device to receive notification with brand new copy of node-pushserver.
