### ISSUE TITLE
ERROR: Error: failed to connect to [undefined:27017]

### ISSUE THREAD

**Issue by jdschuitemaker** [Smile-SA/node-pushserver#66]
When I start the node-pushserver and open the page to send notifications I see that the node-pushserver is logging this error: ERROR: Error: failed to connect to [undefined:27017]

It seems that is happens when the blue badge with "loading users" is shown.

I googled for the error and found that it could be related to mongodb, but it seems to technical for me to solve this myself.

Any hints what could be wrong?

**Comment by marob** [comment]
Have you followed the [1 - Database](https://github.com/Smile-SA/node-pushserver#1---database) instruction?
If you want a version that doesn't require the mongodb dependency, you can try a still in development version using sqlite (no installation required) here: https://github.com/marob/node-pushserver

**Comment by jdschuitemaker** [comment]
Sorry, the database was the problem. Thank you!
