### ISSUE TITLE
user removed if I used send notification [Android]

### ISSUE THREAD

**Issue by mrhaxic** [Smile-SA/node-pushserver#74]
Hi,

I added device token by subscribe and the user is listed in GET `/users` then I tried to push a notification for that user, after succeed the user is removed while am using `/users/{user}/associations`

Any support please?

**Comment by marob** [comment]
Devices are removed if GCM return one of the following error: `InvalidRegistration` or `NotRegistered` (see https://github.com/Smile-SA/node-pushserver/blob/master/lib/GCMPusher.js#L43).
Why? Maybe the saved token is incorrect (see https://developers.google.com/cloud-messaging/http-server-ref#error-codes)?

Did the device received the sent notification?

**Comment by mrhaxic** [comment]
Hi @marob no it doesn't receive it, and I used GCM API with that token and get this response

```
{
    "multicast_id": 5894738133250081198,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1499348819743955%f17171eef9fd7ecd"
        }
    ]
}
```

which it means the token is correct

**Comment by mrhaxic** [comment]
You are right, I checked deeply in the token and it was incorrect. +1
