### ISSUE TITLE
unsubscribe one token

### ISSUE THREAD

**Issue by mrhaxic** [Smile-SA/node-pushserver#75]
Hello,

What is the solution to remove one token only from (user) which is consider as a group ?

Regards

**Comment by marob** [comment]
Hi,

I don't understand the question... isn't the answer in the doc? https://github.com/Smile-SA/node-pushserver#unsubscribe

What is a group?

Regards

**Comment by mrhaxic** [comment]
Hi @marob 

I mean if I subscribe many tokens in a one user for example [**user1**] then I want to unsubscribe/remove only one token from that user

**user1** consider as a group and we can get all tokens by `users/user/associations`

**Comment by marob** [comment]
I don't know what to say... just read the doc:

> ```
> http://domain:port/unsubscribe (POST)
> ```
> + The content-type must be 'application/json'.
> + Format:
> ```js
> {
>   "token":"CAFEBABE"
> }
> ```
> or
> ```js
> {
>   "user":"user1"
> }
> ```
> 
> + You can unsubscribe either a particular device, or all the devices for one user

**Comment by mrhaxic** [comment]
I thought there is a misunderstanding, Let's say you have a group in chat application and the group having 10 members. I use subscribe API to subscribe all members of this group so that's group will have devices. Then one of the members left this group so I need to remove his/her device from that user.

**Comment by marob** [comment]
Well, there is a misunderstanding as there is no group management in node-pushserver.

A **user** has one or many token(s). You can remove a token or a user with all this tokens. That's all.

In the case of your chat application, I suppose every user of the group has its own phone. So each user of the group should be a user in node-pushserver and should have one (or several) token(s).

If you want to be able to notify all users of a group at one, you should manage it in your own server-side application that would:
- manage user-group relationship
- use node-pushserver to send notifications to a list of users (those of a same group)

**Comment by mrhaxic** [comment]
Thanks for your clarification and sorry for misunderstood.

Regards

**Comment by marob** [comment]
You're welcome
